baseURL = 'https://konate.tech/'
locale = 'en-us'
title = 'Konaté Tech B.V.'

[params]
  brand = 'Konaté Tech'
  legalName = 'Konaté Tech B.V.'
  email = 'ornella@konate.tech'
  city = 'Amsterdam, NL'
  kvk = '92366228'
  vat = 'NL866021735B01'

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'Case Studies'
    pageRef = '/case-studies'
    weight = 20

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'
