baseURL = 'https://konate.tech/'
locale = 'en-us'
title = 'Konaté Tech B.V.'

[params]
  brand = 'Konaté Tech'
  email = 'ornella@konate.tech'

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'Case Studies'
    pageRef = '/case-studies'
    weight = 20

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'
